/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlbh.ui;

import com.qlbh.utils.XImage;

/**
 *
 * @author HAN-PC
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        
        setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_ImageUser = new javax.swing.JLabel();
        lbl_Role = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        lbl_FullName = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        pnl_Slide = new javax.swing.JPanel();
        btn_Dot1 = new javax.swing.JButton();
        btn_Dot2 = new javax.swing.JButton();
        btn_Dot3 = new javax.swing.JButton();
        btn_Dot4 = new javax.swing.JButton();
        btn_PrevSlide = new javax.swing.JButton();
        btn_NextSlide = new javax.swing.JButton();
        lbl_Slide1 = new javax.swing.JLabel();
        lbl_Slide2 = new javax.swing.JLabel();
        lbl_Slide3 = new javax.swing.JLabel();
        lbl_Slide4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_Home = new javax.swing.JButton();
        btn_EmployeeManagement = new javax.swing.JButton();
        btn_CustomerManagement = new javax.swing.JButton();
        btn_AccountManagement = new javax.swing.JButton();
        btn_ShippingManagement = new javax.swing.JButton();
        btn_InventoryManagement = new javax.swing.JButton();
        btn_IntergradedManagement = new javax.swing.JButton();
        btn_OrderManagement = new javax.swing.JButton();
        btn_Account = new javax.swing.JButton();
        btn_Setting = new javax.swing.JButton();
        btn_LogOut = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        pnl_Main = new javax.swing.JPanel();
        pnl_Home = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_OrderManagement = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHOP MANAGEMENT");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_ImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/user_120px.png"))); // NOI18N

        lbl_Role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Role.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Role.setText("EMPLOYEE");

        lbl_ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ID.setText("ID: NV001");

        lbl_FullName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_FullName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_FullName.setText("FULLNAME: NGUYỄN VĂN TÈO");

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Email.setText("EMAIL: teonv@gmail.com ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_ImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_Role, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbl_Role)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_FullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Email)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Slide.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Slide.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        pnl_Slide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Dot1.setBackground(new java.awt.Color(242, 242, 242));
        btn_Dot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/new_moon_15px.png"))); // NOI18N
        btn_Dot1.setBorder(null);
        btn_Dot1.setBorderPainted(false);
        btn_Dot1.setContentAreaFilled(false);
        btn_Dot1.setFocusPainted(false);
        pnl_Slide.add(btn_Dot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        btn_Dot2.setBackground(new java.awt.Color(242, 242, 242));
        btn_Dot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/new_moon_15px.png"))); // NOI18N
        btn_Dot2.setBorder(null);
        btn_Dot2.setBorderPainted(false);
        btn_Dot2.setContentAreaFilled(false);
        btn_Dot2.setFocusPainted(false);
        pnl_Slide.add(btn_Dot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        btn_Dot3.setBackground(new java.awt.Color(242, 242, 242));
        btn_Dot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/new_moon_15px.png"))); // NOI18N
        btn_Dot3.setBorder(null);
        btn_Dot3.setBorderPainted(false);
        btn_Dot3.setContentAreaFilled(false);
        btn_Dot3.setFocusPainted(false);
        pnl_Slide.add(btn_Dot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        btn_Dot4.setBackground(new java.awt.Color(242, 242, 242));
        btn_Dot4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/new_moon_gray_15px.png"))); // NOI18N
        btn_Dot4.setBorder(null);
        btn_Dot4.setBorderPainted(false);
        btn_Dot4.setContentAreaFilled(false);
        btn_Dot4.setFocusPainted(false);
        pnl_Slide.add(btn_Dot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        btn_PrevSlide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/back_50px.png"))); // NOI18N
        btn_PrevSlide.setBorderPainted(false);
        btn_PrevSlide.setContentAreaFilled(false);
        btn_PrevSlide.setFocusPainted(false);
        pnl_Slide.add(btn_PrevSlide, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btn_NextSlide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/forward_50px.png"))); // NOI18N
        btn_NextSlide.setBorderPainted(false);
        btn_NextSlide.setContentAreaFilled(false);
        btn_NextSlide.setFocusPainted(false);
        pnl_Slide.add(btn_NextSlide, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, -1, -1));

        lbl_Slide1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Slide1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Slide1.setText("COMING SOON");
        pnl_Slide.add(lbl_Slide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 190));

        lbl_Slide2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Slide2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Slide2.setText("COMING SOON");
        pnl_Slide.add(lbl_Slide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 190));

        lbl_Slide3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Slide3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Slide3.setText("COMING SOON");
        pnl_Slide.add(lbl_Slide3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 190));

        lbl_Slide4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Slide4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Slide4.setText("COMING SOON");
        pnl_Slide.add(lbl_Slide4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 190));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_Slide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Slide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(255, 204, 153)));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_Home.setBackground(new java.awt.Color(255, 204, 153));
        btn_Home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/home_page_40px.png"))); // NOI18N
        btn_Home.setText("HOME");
        btn_Home.setAlignmentY(10.0F);
        btn_Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Home.setContentAreaFilled(false);
        btn_Home.setOpaque(true);

        btn_EmployeeManagement.setBackground(new java.awt.Color(204, 229, 255));
        btn_EmployeeManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_EmployeeManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/valet_40px.png"))); // NOI18N
        btn_EmployeeManagement.setText("EMPLOYEE MANAGEMENT");
        btn_EmployeeManagement.setAlignmentY(10.0F);
        btn_EmployeeManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_EmployeeManagement.setContentAreaFilled(false);
        btn_EmployeeManagement.setOpaque(true);

        btn_CustomerManagement.setBackground(new java.awt.Color(204, 229, 255));
        btn_CustomerManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CustomerManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/reception_40px.png"))); // NOI18N
        btn_CustomerManagement.setText("CUSTOMER MANAGEMENT");
        btn_CustomerManagement.setAlignmentY(10.0F);
        btn_CustomerManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_CustomerManagement.setContentAreaFilled(false);
        btn_CustomerManagement.setOpaque(true);

        btn_AccountManagement.setBackground(new java.awt.Color(204, 229, 255));
        btn_AccountManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_AccountManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/time_management_35px.png"))); // NOI18N
        btn_AccountManagement.setText("ACCOUNT MANAGEMENT");
        btn_AccountManagement.setAlignmentY(10.0F);
        btn_AccountManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_AccountManagement.setContentAreaFilled(false);
        btn_AccountManagement.setOpaque(true);

        btn_ShippingManagement.setBackground(new java.awt.Color(204, 229, 255));
        btn_ShippingManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ShippingManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/supplier_45px.png"))); // NOI18N
        btn_ShippingManagement.setText("SHIPPING MANAGEMENT");
        btn_ShippingManagement.setAlignmentY(10.0F);
        btn_ShippingManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_ShippingManagement.setContentAreaFilled(false);
        btn_ShippingManagement.setOpaque(true);

        btn_InventoryManagement.setBackground(new java.awt.Color(204, 229, 255));
        btn_InventoryManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_InventoryManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/warehouse_35px.png"))); // NOI18N
        btn_InventoryManagement.setText("INVENTORY MANAGEMENT");
        btn_InventoryManagement.setAlignmentY(10.0F);
        btn_InventoryManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_InventoryManagement.setContentAreaFilled(false);
        btn_InventoryManagement.setOpaque(true);

        btn_IntergradedManagement.setBackground(new java.awt.Color(204, 229, 255));
        btn_IntergradedManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_IntergradedManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/chart_45px.png"))); // NOI18N
        btn_IntergradedManagement.setText("INTERGRATED MANAGEMENT");
        btn_IntergradedManagement.setAlignmentY(10.0F);
        btn_IntergradedManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_IntergradedManagement.setContentAreaFilled(false);
        btn_IntergradedManagement.setOpaque(true);

        btn_OrderManagement.setBackground(new java.awt.Color(204, 229, 255));
        btn_OrderManagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_OrderManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/order_history_35px.png"))); // NOI18N
        btn_OrderManagement.setText("ORDER MANAGEMENT");
        btn_OrderManagement.setAlignmentY(10.0F);
        btn_OrderManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_OrderManagement.setContentAreaFilled(false);
        btn_OrderManagement.setOpaque(true);

        btn_Account.setBackground(new java.awt.Color(204, 229, 255));
        btn_Account.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/account_35px.png"))); // NOI18N
        btn_Account.setText("ACCOUNT");
        btn_Account.setAlignmentY(10.0F);
        btn_Account.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Account.setContentAreaFilled(false);
        btn_Account.setOpaque(true);

        btn_Setting.setBackground(new java.awt.Color(204, 229, 255));
        btn_Setting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/settings_45px.png"))); // NOI18N
        btn_Setting.setText("SETTING");
        btn_Setting.setAlignmentY(10.0F);
        btn_Setting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Setting.setContentAreaFilled(false);
        btn_Setting.setOpaque(true);

        btn_LogOut.setBackground(new java.awt.Color(204, 229, 255));
        btn_LogOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/Logout_35px.png"))); // NOI18N
        btn_LogOut.setText("LOG OUT");
        btn_LogOut.setAlignmentY(10.0F);
        btn_LogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_LogOut.setContentAreaFilled(false);
        btn_LogOut.setOpaque(true);

        btn_Exit.setBackground(new java.awt.Color(204, 229, 255));
        btn_Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/shutdown_35px.png"))); // NOI18N
        btn_Exit.setText("EXIT");
        btn_Exit.setAlignmentY(10.0F);
        btn_Exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Exit.setContentAreaFilled(false);
        btn_Exit.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_EmployeeManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_CustomerManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_AccountManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_ShippingManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_InventoryManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_IntergradedManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addComponent(btn_OrderManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_EmployeeManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_CustomerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_AccountManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_ShippingManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_InventoryManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_IntergradedManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_OrderManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Setting, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_Main.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Home.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Home.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TIME WORK (8-16h)", null, null, null, null, null, null, null},
                {"SHIPPING", null, null, null, null, null, null, null},
                {"WAREHOUSE", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setName(""); // NOI18N
        jTable1.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1269, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/home/notification_60px.png"))); // NOI18N
        jLabel1.setText("NOTIFICATION");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_HomeLayout = new javax.swing.GroupLayout(pnl_Home);
        pnl_Home.setLayout(pnl_HomeLayout);
        pnl_HomeLayout.setHorizontalGroup(
            pnl_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_HomeLayout.setVerticalGroup(
            pnl_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_HomeLayout.createSequentialGroup()
                .addGap(0, 448, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnl_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_HomeLayout.createSequentialGroup()
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(221, Short.MAX_VALUE)))
        );

        pnl_Main.add(pnl_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 670));

        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, 30));
        jPanel8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order By", "Item 2", "Item 3", "Item 4" }));

        jButton13.setText("ADD");

        jButton14.setText("DELETE");

        jButton15.setText("EDIT");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Order Management");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Custtomer ID", "Customer Name", "Product ID", "Product Name", "Date", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(493, 493, 493)
                .addComponent(jLabel7)
                .addContainerGap(536, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Order Management", jPanel11);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Order Details", jPanel13);

        javax.swing.GroupLayout pnl_OrderManagementLayout = new javax.swing.GroupLayout(pnl_OrderManagement);
        pnl_OrderManagement.setLayout(pnl_OrderManagementLayout);
        pnl_OrderManagementLayout.setHorizontalGroup(
            pnl_OrderManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        pnl_OrderManagementLayout.setVerticalGroup(
            pnl_OrderManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_OrderManagementLayout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_Main.add(pnl_OrderManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 670));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Account;
    private javax.swing.JButton btn_AccountManagement;
    private javax.swing.JButton btn_CustomerManagement;
    private javax.swing.JButton btn_Dot1;
    private javax.swing.JButton btn_Dot2;
    private javax.swing.JButton btn_Dot3;
    private javax.swing.JButton btn_Dot4;
    private javax.swing.JButton btn_EmployeeManagement;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_IntergradedManagement;
    private javax.swing.JButton btn_InventoryManagement;
    private javax.swing.JButton btn_LogOut;
    private javax.swing.JButton btn_NextSlide;
    private javax.swing.JButton btn_OrderManagement;
    private javax.swing.JButton btn_PrevSlide;
    private javax.swing.JButton btn_Setting;
    private javax.swing.JButton btn_ShippingManagement;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_FullName;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_ImageUser;
    private javax.swing.JLabel lbl_Role;
    private javax.swing.JLabel lbl_Slide1;
    private javax.swing.JLabel lbl_Slide2;
    private javax.swing.JLabel lbl_Slide3;
    private javax.swing.JLabel lbl_Slide4;
    private javax.swing.JPanel pnl_Home;
    private javax.swing.JPanel pnl_Main;
    private javax.swing.JPanel pnl_OrderManagement;
    private javax.swing.JPanel pnl_Slide;
    // End of variables declaration//GEN-END:variables
}
