/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlbh.ui;

/**
 *
 * @author pc
 */
public class loading extends javax.swing.JFrame {

    /**
     * Creates new form loading
     */
    public loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        pgb_loading = new javax.swing.JProgressBar();
        lbl_anh_loading = new javax.swing.JLabel();
        Btn_dot4 = new javax.swing.JButton();
        Btn_dot1 = new javax.swing.JButton();
        Btn_dot2 = new javax.swing.JButton();
        Btn_dot3 = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pgb_loading.setValue(50);
        pgb_loading.setStringPainted(true);
        jPanel1.add(pgb_loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 662, 1240, 44));

        lbl_anh_loading.setBackground(new java.awt.Color(255, 51, 51));
        lbl_anh_loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_anh_loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/icon/loading/z3442359022391_8b836899d0f5dd54ed0085868cb601ea.jpg"))); // NOI18N
        lbl_anh_loading.setText("HÌNH");
        jPanel1.add(lbl_anh_loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1230, 550));

        Btn_dot4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_dot4.setBorder(null);
        Btn_dot4.setBorderPainted(false);
        Btn_dot4.setContentAreaFilled(false);
        Btn_dot4.setFocusPainted(false);
        Btn_dot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_dot4ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_dot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, 20, 20));

        Btn_dot1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_dot1.setBorder(null);
        Btn_dot1.setBorderPainted(false);
        Btn_dot1.setContentAreaFilled(false);
        Btn_dot1.setFocusPainted(false);
        Btn_dot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_dot1ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_dot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, 20, 20));

        Btn_dot2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_dot2.setBorder(null);
        Btn_dot2.setBorderPainted(false);
        Btn_dot2.setContentAreaFilled(false);
        Btn_dot2.setFocusPainted(false);
        Btn_dot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_dot2ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_dot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, 20, 20));

        Btn_dot3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_dot3.setBorder(null);
        Btn_dot3.setBorderPainted(false);
        Btn_dot3.setContentAreaFilled(false);
        Btn_dot3.setFocusPainted(false);
        Btn_dot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_dot3ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_dot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1318, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_dot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_dot4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dot4ActionPerformed

    private void Btn_dot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_dot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dot1ActionPerformed

    private void Btn_dot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_dot2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dot2ActionPerformed

    private void Btn_dot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_dot3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dot3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_dot1;
    private javax.swing.JButton Btn_dot2;
    private javax.swing.JButton Btn_dot3;
    private javax.swing.JButton Btn_dot4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lbl_anh_loading;
    private javax.swing.JProgressBar pgb_loading;
    // End of variables declaration//GEN-END:variables
}
